version: "3.9"

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./var/lib/postgresql/data/
    ports:
      - "5432:5432"
  db_test:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./var/lib/postgresql/data_test/ 
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - .:/code/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: 'postgres://postgres:postgres@db:5432/postgres'
      DATABASE_URL_TEST: 'postgres://postgres:postgres@db_test:5432/postgres_test'
