# Generated by Django 4.1.4 on 2023-02-10 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor_compra', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('metodo_pagamento', models.CharField(choices=[('cartao_debito', 'Cartão de Débito'), ('cartao_credito', 'Cartão de Crédito'), ('pix', 'Pix')], max_length=20)),
                ('frete', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('estoque', models.IntegerField()),
                ('score', models.FloatField()),
                ('imagem', models.ImageField(upload_to='produtos/')),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=0, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produto_checkout', to='game.produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrinho_checkout', to='game.carrinho')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'PRODUTOS',
            },
        ),
    ]
